/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quarantined records */
        get: operations["admin_list_quarantine_quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sync/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List past sync runs */
        get: operations["admin_list_sync_runs_sync_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sync/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a sync from an HRIS source */
        post: operations["admin_run_sync_route_sync__source__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an employee */
        get: operations["employees_get_employee_route__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The full tenant org graph */
        get: operations["graph_get_graph_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a position */
        get: operations["positions_get_position__position_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/positions/{position_id}/descendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Solid-line subtree below a position */
        get: operations["positions_get_descendants__position_id__descendants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/reporting-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a reporting line */
        post: operations["reporting_lines_add_reporting_line_post"];
        /** Remove a reporting line */
        delete: operations["reporting_lines_remove_reporting_line_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations */
        get: operations["organizations_list_organizations__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["health_healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check (verifies Mongo connectivity) */
        get: operations["health_readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompensationOut */
        CompensationOut: {
            /**
             * Amount
             * Format: decimal
             */
            amount: string;
            /** Currency */
            currency: string;
        };
        /** DescendantOut */
        DescendantOut: {
            /** Department */
            department: string;
            /**
             * Depth
             * @description Hops from the queried position, via solid lines only
             */
            depth: number;
            /**
             * Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            id: string;
            /** Reports To */
            reports_to: components["schemas"]["ReportsToEdge"][];
            status: components["schemas"]["PositionStatus"];
            /** Title */
            title: string;
        };
        /** DescendantsOut */
        DescendantsOut: {
            /** Results */
            results: components["schemas"]["DescendantOut"][];
        };
        /** EdgeOut */
        EdgeOut: {
            /** Is Primary */
            is_primary: boolean;
            /**
             * Manager Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            manager_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "solid" | "dotted";
            /**
             * Report Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            report_id: string;
        };
        /** EmployeeHROut */
        EmployeeHROut: {
            compensation: components["schemas"]["CompensationOut"];
            /**
             * Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            id: string;
            /** Name */
            name: string;
            /** Title */
            title: string | null;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /**
             * Error
             * @description A stable machine-readable error code, e.g. 'not_found'
             */
            error: string;
            /** Message */
            message: string;
        };
        /** GraphOut */
        GraphOut: {
            /** Edges */
            edges: components["schemas"]["EdgeOut"][];
            /** Nodes */
            nodes: components["schemas"]["NodeOut"][];
            /** Root Ids */
            root_ids: string[];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** NodeOut */
        NodeOut: {
            /** Department */
            department: string;
            /**
             * Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            id: string;
            /**
             * Occupants
             * @default null
             */
            occupants: components["schemas"]["OccupantOut"][] | null;
            status: components["schemas"]["PositionStatus"];
            /** Title */
            title: string;
        };
        /** OccupantOut */
        OccupantOut: {
            /**
             * Employee Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            employee_id: string;
            /** Fte */
            fte: number;
            /** Is Primary */
            is_primary: boolean;
            /** Name */
            name: string;
        };
        /** OrganizationOut */
        OrganizationOut: {
            /**
             * Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            id: string;
            /** Name */
            name: string;
        };
        /** OrganizationsOut */
        OrganizationsOut: {
            /** Results */
            results: components["schemas"]["OrganizationOut"][];
        };
        /** PositionOut */
        PositionOut: {
            /** Department */
            department: string;
            /**
             * Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            id: string;
            /** Reports To */
            reports_to: components["schemas"]["ReportsToEdge"][];
            status: components["schemas"]["PositionStatus"];
            /** Title */
            title: string;
        };
        /**
         * PositionStatus
         * @enum {string}
         */
        PositionStatus: "active" | "vacant" | "closed";
        /** QuarantineListOut */
        QuarantineListOut: {
            /** Results */
            results: components["schemas"]["QuarantineOut"][];
        };
        /** QuarantineOut */
        QuarantineOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Errors */
            errors: string[];
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
            /** Source */
            source: string;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Mongo */
            mongo: string;
            /** Status */
            status: string;
        };
        /** ReportingLineDeleteIn */
        ReportingLineDeleteIn: {
            /**
             * Manager Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            manager_id: string;
            /**
             * Report Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            report_id: string;
        };
        /** ReportingLineIn */
        ReportingLineIn: {
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            /**
             * Manager Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            manager_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "solid" | "dotted";
            /**
             * Report Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            report_id: string;
        };
        /** ReportsToEdge */
        ReportsToEdge: {
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            /**
             * Position Id
             * Format: objectid
             * @example 507f1f77bcf86cd799439011
             */
            position_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "solid" | "dotted";
        };
        /** SyncRunOut */
        SyncRunOut: {
            /** Created Count */
            created_count: number;
            /** Duration Ms */
            duration_ms: number;
            /** Quarantined Count */
            quarantined_count: number;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Unchanged Count */
            unchanged_count: number;
            /** Updated Count */
            updated_count: number;
        };
        /** SyncRunsOut */
        SyncRunsOut: {
            /** Results */
            results: components["schemas"]["SyncRunOut"][];
        };
        /** ValidationErrorModel */
        ValidationErrorModel: {
            /**
             * Error context
             * @description An optional object which contains values required to render the error message.
             * @default null
             */
            ctx: {
                [key: string]: unknown;
            } | null;
            /**
             * Input
             * @description The input provided for validation.
             */
            input: unknown;
            /**
             * Location
             * @description The error's location as a list.
             */
            loc: unknown[];
            /**
             * Message
             * @description A human readable explanation of the error.
             */
            msg: string;
            /**
             * Error Type
             * @description A computer-readable identifier of the error type.
             */
            type: string;
            /**
             * URL
             * @description The URL to further information about the error.
             * @default null
             */
            url: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_list_quarantine_quarantine_get: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineListOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_list_sync_runs_sync_runs_get: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunsOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    admin_run_sync_route_sync__source__post: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path: {
                source: "workday_like" | "bamboo_like";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    employees_get_employee_route__employee_id__get: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path: {
                /** @example 507f1f77bcf86cd799439011 */
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeHROut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    graph_get_graph_graph_get: {
        parameters: {
            query?: {
                view?: "positions" | "people";
                as_of?: string | null;
            };
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    positions_get_position__position_id__get: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path: {
                /** @example 507f1f77bcf86cd799439011 */
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    positions_get_descendants__position_id__descendants_get: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path: {
                /** @example 507f1f77bcf86cd799439011 */
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DescendantsOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    reporting_lines_add_reporting_line_post: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportingLineIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    reporting_lines_remove_reporting_line_delete: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Interim pre-auth tenant id - replaced by a JWT claim in Phase 4
                 * @example 507f1f77bcf86cd799439011
                 */
                x_org_id: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportingLineDeleteIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    organizations_list_organizations__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationsOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    health_healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
        };
    };
    health_readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorModel"][];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
}
